"""Generate dbt artifacts from ``config/datasets.yml`` so the catalog stays the single source of truth.

Writes (and with ``check=True`` only verifies):
  * ``dbt/models/staging/zillow/_zillow__sources.yml`` - source tables with docs and metadata
  * ``dbt/macros/generated/zillow_catalog.sql``          - parse-time list the staging unions loop over
  * ``dbt/seeds/zillow_datasets.csv``                    - dataset dimension for the marts
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path

import yaml

from proptech.catalog import Catalog, Kind

HEADER = "# Generated by `proptech dbt-sources` from config/datasets.yml. Do not edit by hand.\n"

SEED_COLUMNS = (
    "dataset_key",
    "family",
    "metric",
    "kind",
    "geography",
    "unit",
    "tier",
    "property_type",
    "bedrooms",
    "is_smoothed",
    "is_seasonally_adjusted",
    "profiles",
    "source_path",
    "description",
)


def _region_columns() -> list[dict[str, str]]:
    return [
        {"name": "region_id", "description": "Zillow RegionID (stable across Zillow datasets)."},
        {
            "name": "size_rank",
            "description": "Zillow's population-based rank within the geography.",
        },
        {"name": "region_name", "description": "Region name; the ZIP code for ZIP files."},
        {"name": "region_type", "description": "country | state | msa | county | city | zip"},
        {"name": "state_name", "description": "Two-letter state code for sub-state geographies."},
        {"name": "state", "description": "Two-letter state code (county/city/ZIP files)."},
        {"name": "city", "description": "City (ZIP files)."},
        {
            "name": "metro",
            "description": "CBSA title the region belongs to (county/city/ZIP files).",
        },
        {"name": "county_name", "description": "County name (city/ZIP files)."},
        {"name": "state_fips", "description": "State FIPS code (county files)."},
        {"name": "county_fips", "description": "County FIPS code (county files)."},
        {"name": "dataset_key", "description": "Catalog key of the file the row came from."},
    ]


def render_sources(catalog: Catalog) -> str:
    tables = []
    for d in catalog.datasets:
        meta = {
            "family": d.family,
            "metric": d.metric,
            "kind": str(d.kind),
            "geography": str(d.geography),
            "unit": d.unit,
            "profiles": list(d.profiles),
            "source_path": d.path,
        }
        if d.kind is Kind.TIMESERIES:
            # No tests on raw sources: extended-profile tables may legitimately not exist.
            # Integrity is tested on the staging models instead.
            columns = [
                {"name": "region_id", "description": "Zillow RegionID."},
                {"name": "date", "description": "Month-end date of the observation."},
                {"name": "value", "description": f"Observed value ({d.unit})."},
            ]
        else:
            columns = [
                {"name": "region_id", "description": "Zillow RegionID."},
                {"name": "base_date", "description": "Month the forecast was made from."},
                {"name": "horizon_date", "description": "Month-end the forecast targets."},
                {
                    "name": "horizon_months",
                    "description": "Months between base_date and horizon_date.",
                },
                {"name": "value", "description": "Forecast percent change from base_date."},
            ]
        tables.append(
            {
                "name": d.raw_table,
                "description": d.description,
                "config": {"meta": meta},
                "columns": columns,
            }
        )
        tables.append(
            {
                "name": d.regions_table,
                "description": f"Region metadata from {d.path}.",
                "config": {"meta": {**meta, "kind": "regions"}},
                "columns": _region_columns(),
            }
        )
        if d.kind is Kind.FORECAST:
            tables.append(
                {
                    "name": f"{d.raw_table}__history",
                    "description": f"Every vintage of {d.key} loaded so far (append-only).",
                    "config": {"meta": {**meta, "kind": "forecast_history"}},
                }
            )
    document = {
        "version": 2,
        "sources": [
            {
                "name": "zillow",
                "description": (
                    "Zillow Research public CSVs (https://www.zillow.com/research/data/), long format."
                ),
                "schema": "{{ env_var('PROPTECH_BQ_DATASET_PREFIX', '') }}raw_zillow",
                "tables": tables,
            }
        ],
    }
    return HEADER + yaml.safe_dump(document, sort_keys=False, width=110, allow_unicode=True)


def render_macro(catalog: Catalog) -> str:
    entries = [
        {
            "key": d.key,
            "family": d.family,
            "metric": d.metric,
            "kind": str(d.kind),
            "geography": str(d.geography),
            "unit": d.unit,
            "profiles": list(d.profiles),
        }
        for d in catalog.datasets
    ]
    body = json.dumps(entries, indent=2)
    return (
        "{#- Generated by `proptech dbt-sources` from config/datasets.yml. Do not edit by hand. -#}\n"
        "{% macro zillow_catalog() %}\n"
        f"  {{{{ return({body}) }}}}\n"
        "{% endmacro %}\n"
    )


def render_seed(catalog: Catalog) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(SEED_COLUMNS)
    for d in catalog.datasets:
        writer.writerow(
            [
                d.key,
                d.family,
                d.metric,
                str(d.kind),
                str(d.geography),
                d.unit,
                d.tier or "",
                d.property_type or "",
                "" if d.bedrooms is None else d.bedrooms,
                str(d.smoothed).lower(),
                str(d.seasonally_adjusted).lower(),
                "|".join(d.profiles),
                d.path,
                d.description,
            ]
        )
    return buffer.getvalue()


def outputs(catalog: Catalog, dbt_dir: Path) -> dict[Path, str]:
    return {
        dbt_dir / "models" / "staging" / "zillow" / "_zillow__sources.yml": render_sources(catalog),
        dbt_dir / "macros" / "generated" / "zillow_catalog.sql": render_macro(catalog),
        dbt_dir / "seeds" / "zillow_datasets.csv": render_seed(catalog),
    }


def sync(catalog: Catalog, dbt_dir: Path, *, check: bool = False) -> list[Path]:
    """Write generated files; with ``check`` return the stale ones instead of writing."""
    stale = []
    for path, content in outputs(catalog, dbt_dir).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    return stale
